# Default values for postgresql-migration.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ghcr.io/robyrobot/bucardo_docker_image
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v5.6.0-nj-1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# bucardo configuration for replication
bucardo: {}
  # # if enabled use debug for bucardo logs
  # debug: true
  # gracePeriodSec: 120
  # syncs:
  #   - name: test1
  #     onetimecopy: 1 # ref: https://bucardo.org/Bucardo/operations/onetimecopy
  #     sources:
  #     - name: test1        
  #       dbname: test1
  #       dbhost: host1.example.com
  #       dbuser: postgres
  #       dbpass: password
  #       includeTables: [] # list of tables to include (can be used pg_dump wildcard)
  #       excludeTables: [] # list of tables to exclude (can be used pg_dump wildcard)
  #     targets:
  #     - name: target1
  #       dbname: target1
  #       dbhost: host2.example.com
  #       dbuser: postgres
  #       dbpass: password
  #       # if enabled it will DROP ALL THE TABLES into ANY TARGET DATABASES and then recteate them from the relative source db defined into sync
  #       # this ensure the source and target db has the same schema.
  #       cleanDb: true
  #       postAction:
  #         # execute some init script needed for the replication. Usually after a db clean
  #         enabled: true
  #         script: |
  #           -- SQL commands if needed
  # 
  # # Experimental feature that automatically add a primary key to sources and targets tables that do not have it.
  # # The column can be safely dropped after the migration complete.
  # fixMissingPrimaryKey: 
  #   enabled: true
  #
  # # Primary key name. Default is __PK__
  #   primaryKey: __PK__ 

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
