apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elastic-migration.fullname" . }}
  labels:
    {{- include "elastic-migration.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "elastic-migration.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "elastic-migration.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "elastic-migration.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-elasticdump
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
            - |
              SCRIPT_PATH=/scripts/
              # source all scripts in SCRIPT_PATH
              for s in $SCRIPT_PATH/*.sh; do
              source $s
              done
                 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: scripts
              mountPath: /scripts/
            # - name: hooks
            #   mountPath: /hooks/
      terminationGracePeriodSeconds: {{ .Values.elasticdump.gracePeriodSec | default 60 }}
      volumes:
        - name: scripts
          configMap:
            name: {{ include "elastic-migration.fullname" . }}-cm-scripts
        # - name: hooks
        #   configMap:
        #     name: {{ include "elastic-migration.fullname" . }}-cm-hooks
        
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
