apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql-migration.fullname" . }}-cm-hooks
  labels:
    {{- include "postgresql-migration.labels" . | nindent 4 }}
data:
    {{- range $path, $bytes := .Files.Glob "hooks/**" }}
    {{- $name := base $path }}
    {{ $name }}: |-
        {{- tpl ($.Files.Get (printf "%s" $path)) $ | nindent 8 }}
    {{- end -}}

{{- if not .Values.bucardo }}
{{- fail "Bucardo session in values must be specified!" }}
{{- end }}
