apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql-migration.fullname" . }}
  labels:
    {{- include "postgresql-migration.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "postgresql-migration.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postgresql-migration.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postgresql-migration.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-bucardo
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe: 
            initialDelaySeconds: 5
            periodSeconds: 10
            exec:
              command:
                - pg_isready
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            exec:
              command:
                - pg_isready
          lifecycle:
            preStop:
              exec:
                command: 
                - /bin/bash
                - -c
                - /media/bucardo/stopHook.sh
                  
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: working
              mountPath: /media/bucardo/
      terminationGracePeriodSeconds: {{ .Values.bucardo.gracePeriodSec | default 60 }}
      initContainers:
        - name: copy
          image: busybox
          command: 
            - sh
            - -c
            - |
                # copy scripts
                cp /config/*.sh /media/bucardo/
                chmod +x /media/bucardo/*.sh
          
          volumeMounts:
          - mountPath: /config/bucardo.sh
            subPath: bucardo.sh
            name: config
          - mountPath: /config/stopHook.sh
            subPath: stopHook.sh
            name: config
          - mountPath: /media/bucardo/
            name: working
      volumes:
        - name: working
          emptyDir: {} 
        - name: config
          configMap:
            name: {{ include "postgresql-migration.fullname" . }}-configmap
        
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
