# apiVersion: apps/v1
# kind: Deployment
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "postgresql-migration.fullname" . }}
  labels:
    {{- include "postgresql-migration.labels" . | nindent 4 }}
spec:
  template:
    metadata:      
      annotations:
        checksum/scripts: {{ include (print $.Template.BasePath "/cm-scripts.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postgresql-migration.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postgresql-migration.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:        
        - name: {{ .Chart.Name }}-bucardo
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # lifecycle:
          #   preStop:
          #     exec:
          #       command: 
          #       - /bin/bash
          #       - -c
          #       - |
          #         source /bucardo/hooks/stopHook.sh
          #livenessProbe: 
            # initialDelaySeconds: 5
            # periodSeconds: 10
            # exec:
            #   command:
            #     - pg_isready
          #readinessProbe: 
            # initialDelaySeconds: 5
            # periodSeconds: 10
            # exec:
            #   command:
            #     - pg_isready

                  
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: scripts
              mountPath: /bucardo/scripts/
            # - name: hooks
            #   mountPath: /bucardo/hooks/
      #terminationGracePeriodSeconds: {{ .Values.bucardo.gracePeriodSec | default 60 }}
      restartPolicy: Never
      volumes:
        - name: scripts
          configMap:
            name: {{ include "postgresql-migration.fullname" . }}-cm-scripts
        # - name: hooks
        #   configMap:
        #     name: {{ include "postgresql-migration.fullname" . }}-cm-hooks
        
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
